version: "3"
services:
  cli:
    user: root
    image: hexo-theme-yun
    container_name: hexo
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        - CHANGE_APK_SOURCE=true              # 更换 APK 源为阿里源
        - CHANGE_NPM_SOURCE=true              # 更换 NPM 源为腾讯源
    working_dir: /blog
    environment:
      - NODE_ENV=production                   # 将 node 的配置切换到生产环境
    volumes:
      - ./_config.yml:/blog/_config.yml       # 挂载根目录配置文件
      - ./themes:/blog/themes                 # 挂载主题目录
      - ./scaffolds:/blog/scaffolds           # 挂载草稿目录
      - ./source:/blog/source                 # 挂载资源目录
      - ./public:/blog/public                 # 挂载 HTML 的生成目录
    ports: 
      - 4000:4000                             # 将 Docker 内的 4000 端口映射到主机的 4000 端口
    command: "sleep 24h"                      # 休眠 shell 24 小时防止容器自动关闭