# Hexo Configuration
# # Docs: https://hexo.io/docs/configuration.html
# # Source: https://github.com/hexojs/hexo/

# Site
title: 云游君的小站
subtitle: All at sea.
description: 希望能成为一个有趣的人
keywords:
  - YunYouJun
  - Blog
  - 云游君
  - 博客
  - 云游君的小站
  - yunyoujun.cn
  - www.yunyoujun.cn
author: 云游君
# language:
#   - zh-CN
#   - en
language: zh-CN
timezone: Asia/Shanghai

# URL
# # If your site is put in a subdirectory, set url as 'https://yoursite.com/child' and root as '/child/'
url: https://www.yunyoujun.cn
root: /
# posts/:name/
permalink: posts/:title/ # :category/:title
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 7
  order_by: -updated
  pagination_dir: page

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
# # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
# Hexo uses Moment.js to parse and display date
# You can customize the date format as defined in
# https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# # updated_option supports 'mtime', 'date', 'empty'
updated_option: mtime

# Pagination
# # Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
# # include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
# Plugins: https://hexo.io/plugins/
# Themes: https://hexo.io/themes/
# Docs: https://yun.yunyoujun.cn
# https://github.com/YunYouJun/hexo-theme-yun
theme: yun

# Deployment
# Docs: https://hexo.io/docs/deployment.html
# https://github.com/hexojs/hexo-deployer-git
deploy:
  type: git
  repo:
    github: https://github.com/YunYouJun/yunyoujun.github.io.git,master
    coding: https://e.coding.net/YunYouJun/yunyoujun.coding.me.git,master
  message:
  extend_dirs:

# plugins
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -updated
  icon: favicon.png
  autodiscovery: true
  template:

# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml

# https://github.com/oncletom/hexo-algolia
algolia:
  applicationID: CJXXAGRCYN
  apiKey: ae1966d2aeab22bf9335679f45d2cd9a
  indexName: my-hexo-blog
  chunkSize: 5000

# https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  quotes: “”‘’
  modifyAnchors: 0
  autolink: true
  mangle: true
  sanitizeUrl: false
  headerIds: true
  lazyload: false
  prependRoot: false
  postAsset: false
  external_link:
    enable: false
    exclude: []
    nofollow: false
  disableNunjucks: false

# https://github.com/hexojs/hexo-server
server:
  compress: true

# https://github.com/MoePlayer/hexo-tag-aplayer
aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.js
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdelivr.net/npm/meting@1/dist/Meting.min.js
  asset_inject: false

# https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  enable: false
  ignore_error: false
  silent: false
  exclude:
css_minifier:
  enable: true
  silent: false
  exclude:
    - '*.min.css'
# we have esbuild!
js_minifier:
  enable: false
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false

# hexo-tag-common
# https://github.com/YunYouJun/hexo-tag-common
tag_common:
  cdn: false
  layout:
    - post
    - page
    # - home

# hexo-widget-tree
# https://github.com/YunYouJun/hexo-widget-tree
widget_tree:
  cdn: true
  hide: false
  layout: tree
  showCount: true
  toc:
    enable: true
    list_number: false
